config/routes.rb
UnicornTest::Application.routes.draw do
  resources :havy_tables

end

app/models/havy_table.rb
class HavyTable < Test::Unicorn::Test::HeavyTable
  attr_accessible :data, :name, :time, :vocal, :content
  
  def content
    self.data
  end
  
  def content=(value)
    self.data = value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/havy_tables_controller.rb
class HavyTablesController < ApplicationController
  # GET /havy_tables
  # GET /havy_tables.json
  def index
    @havy_tables = HavyTable.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @havy_tables }
    end
  end

  # GET /havy_tables/1
  # GET /havy_tables/1.json
  def show
    @havy_table = HavyTable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @havy_table }
    end
  end

  # GET /havy_tables/new
  # GET /havy_tables/new.json
  def new
    @havy_table = HavyTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @havy_table }
    end
  end

  # GET /havy_tables/1/edit
  def edit
    @havy_table = HavyTable.find(params[:id])
  end

  # POST /havy_tables
  # POST /havy_tables.json
  def create
    @havy_table = HavyTable.new(params[:havy_table])

    respond_to do |format|
      if @havy_table.save
        format.html { redirect_to @havy_table, notice: 'Havy table was successfully created.' }
        format.json { render json: @havy_table, status: :created, location: @havy_table }
      else
        format.html { render action: "new" }
        format.json { render json: @havy_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /havy_tables/1
  # PUT /havy_tables/1.json
  def update
    @havy_table = HavyTable.find(params[:id])
    
    respond_to do |format|
      if @havy_table.update_attributes(params[:havy_table])
        format.html { redirect_to @havy_table, notice: 'Havy table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @havy_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /havy_tables/1
  # DELETE /havy_tables/1.json
  def destroy
    @havy_table = HavyTable.find(params[:id])
    @havy_table.destroy

    respond_to do |format|
      format.html { redirect_to havy_tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/havy_tables_helper.rb
module HavyTablesHelper
end

app/views/havy_tables/_form.html.erb
<%= form_for(@havy_table) do |f| %>
  <% if @havy_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@havy_table.errors.count, "error") %> prohibited this havy_table from being saved:</h2>

      <ul>
      <% @havy_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.file_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/havy_tables/edit.html.erb
<h1>Editing havy_table</h1>

<%= render 'form' %>

<%= link_to 'Show', @havy_table %> |
<%= link_to 'Back', havy_tables_path %>

app/views/havy_tables/index.html.erb
<h1>Listing havy_tables</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @havy_tables.each do |havy_table| %>
  <tr>
    <td><%= havy_table.name %></td>
    <td><%= link_to 'Show', havy_table %></td>
    <td><%= link_to 'Edit', edit_havy_table_path(havy_table) %></td>
    <td><%= link_to 'Destroy', havy_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Havy table', new_havy_table_path %>

app/views/havy_tables/new.html.erb
<h1>New havy_table</h1>

<%= render 'form' %>

<%= link_to 'Back', havy_tables_path %>

app/views/havy_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @havy_table.name %>
</p>

<p>
  <b>Content:</b>
  <%= @havy_table.content %>
</p>


<%= link_to 'Edit', edit_havy_table_path(@havy_table) %> |
<%= link_to 'Back', havy_tables_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UnicornTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>